### ISSUE TITLE
Issue 1: User can view top 50 stocks being discussed

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the top 50 stocks being discussed on the popular subreddit, Wall Street Bets. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to view 3 posts per row on desktop, and one post per row on mobile. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-15 at 5 32 52 PM](https://user-images.githubusercontent.com/65789518/173964479-763e7c0d-e74a-4f29-acea-2660cc75b0c5.png)
![Screen Shot 2022-06-15 at 5 33 13 PM](https://user-images.githubusercontent.com/65789518/173964490-71d189ab-6189-47ad-9ab1-760f0eb4f0fd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="stonks"] to the HTML. 
- [x] Ensure the view looks nice on both mobile-sized and desktop-sized screens.
- [x] Create DOM tree for rendered cards.
- [x] Ensure data from API is populating correctly.
- [x] Add the postID to the object.
- [x] Increment the postID on the data model. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
