### ISSUE TITLE
Issue 2: User can add to watchlist

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can indicate if they own a particular stock and add a stock to a watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A selectable checkbox gives the users the ability to specify if they own a particular stock, and a watch button which allows the user to add any stock to a watchlist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-17 at 1 30 04 PM](https://user-images.githubusercontent.com/65789518/174404862-370f2ac3-8a15-4fb8-8cba-183cbd5124c6.png)
![Screen Shot 2022-06-17 at 1 30 13 PM](https://user-images.githubusercontent.com/65789518/174404877-9c1c41cd-0cd4-4b15-a65a-ba8470e10887.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add checkbox to specify if the user owns the stock
- [x] Add watch button
- [x] Add sibling div[data-view] for 'watchlist' view
- [x] Assign watch button to stock ID
- [x] Set up local storage
- [x] Ensure data saves when refreshed
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
