### ISSUE TITLE
Issue 3: User can switch views

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view stocks they've saved to their Watchlist, and toggle between both views. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can see the top 50 stocks being discussed, and if they've added any stocks to their watch list, be able to view them. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-23 at 5 39 54 PM](https://user-images.githubusercontent.com/65789518/175437583-a7f7973b-abdc-4175-826a-c5b0c7322a51.png)
![Screen Shot 2022-06-23 at 5 40 04 PM](https://user-images.githubusercontent.com/65789518/175437591-80614c82-9c1c-4c32-a57c-3d584075e153.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add anchor tag in header
- [x] Query select for data views
- [x] Add HTML for Watchlist view
- [x] Add hidden CSS class to toggle views
- [x] Add function for view swapping
- [x] Ensure 'watched' posts render in Watchlist
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
