### ISSUE TITLE
Issue 4: User can specify if they've sold a stock

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
The user can specify if they own or sold the given stock from the Watchlist

User can specify if they've sold a stock from the Watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user switches to the Watchlist that contains a stock they own, they can update it to 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-24 at 12 46 56 PM](https://user-images.githubusercontent.com/65789518/175658071-aec0b97c-fb86-40f9-8d82-b43d1b8948d9.png)
![Screen Shot 2022-06-24 at 12 46 52 PM](https://user-images.githubusercontent.com/65789518/175658074-4a90fadc-fdf2-44c2-9506-266957a1b517.png)
![Screen Shot 2022-06-24 at 12 46 44 PM](https://user-images.githubusercontent.com/65789518/175658077-3fa72b6c-8d0e-4f4a-920e-130cf5728bcd.png)
![Screen Shot 2022-06-24 at 12 46 33 PM](https://user-images.githubusercontent.com/65789518/175658078-cd98ece3-a065-4a02-8b1d-ef8bc62bc427.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Assign ID's to watchlist stocks
- [ ] Same ID's should apply to stock inputs
- [ ] Update data model when checkbox is clicked
- [ ] Render delete button
- [ ] Assign ID to delete button
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
